"""PIN — Pinned Inference on Flop (pin/1)."""

PIN_VERSION = "pin/1"
FLOP_CHALLENGE_WINDOW_SEC = 7 * 24 * 60 * 60
TOPLOC_BYTES_PER_SLICE = 258
TOPLOC_TOKENS_PER_SLICE = 32
DISPUTE_BOND_FLOP = 100

__all__ = [
    "PIN_VERSION",
    "FLOP_CHALLENGE_WINDOW_SEC",
    "TOPLOC_BYTES_PER_SLICE",
    "TOPLOC_TOKENS_PER_SLICE",
    "DISPUTE_BOND_FLOP",
]
